account/urls.py
from django.conf.urls import url
from . import views
# from paystack import views as v
from django.contrib.auth import views as v
from django.urls import path
from bizz import views as bv

app_name='account'

urlpatterns = [
    url(r'^$', views.stream, name='stream'),
    url(r'^home/$', views.market, name='market'),
    url(r'^category/(?P<category>[-\w]+)/$', views.market, name='market_category'),
    url(r'^sign-in/', v.LoginView.as_view(), name='login'),
    url(r'^sign-out/', v.LogoutView.as_view(), name='logout'),
    url(r'^logout-then-login/$', v.logout_then_login, name='logout_then_login'),
    url(r'^password-change/$', v.PasswordChangeView.as_view(), {'post_change_redirect' : 'account:password_change_done'}, name='password_change'),
    url(r'^password-change/done/$', v.PasswordChangeDoneView.as_view(), name='password_change_done'),
    url(r'^password-reset/$', v.PasswordResetView.as_view(), {'post_reset_redirect':'account:password_reset_done'}, name='password_reset'),
    url(r'^password-reset/done$', v.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', v.PasswordResetConfirmView.as_view(), {'post_reset_redirect':'account:login'} ,name='password_reset_confirm'),
    url(r'^password-reset/complete/$', v.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    url(r'^register/$', views.register, name='register'),
    url(r'^user-follow/$', views.follow, name='follow'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.market,name='post_list_by_tag'),
    url(r'^edit/$', views.edit, name='edit'),
    url(r'^terms-and-conditions/$', views.terms, name='term'),
    url(r'^contact-us/$', views.contact, name='contact'),
    url(r'^success/$', views.success, name='success'),
    url(r'^failure/$', views.failure, name='failure'),
    path('<int:id>/', bv.detail, name='detail'),
    path("<str:username>/", views.profile, name='profile'),
    # url(r'^(?P<username>[-\w]+)/$', views.profile, name='profile'),
    #url(r'^(?P<business_name>[-\w]+)/', views.profile1, name='profile1'),
    url(r'^filter/(?P<market>[-\w]+)/$', views.filter_shops, name='filter'),
    url(r'^favourites/(?P<user_id>\d+)/$', views.favourites, name='favourites'),
    url(r'^market/(?P<market>[-\w]+)/$', views.filter_shops, name='farmcenter'),
    url(r'(?P<username>[-\w]+)/followers/', views.followers, name='followers'),
    url(r'(?P<username>[-\w]+)/following/', views.following, name='following'),
    url(r'self-delete/(?P<admin_id>\d+)/', views.self_delete, name='delete'),
                                                       
]

bizz/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name='bizz'

urlpatterns = [
    url(r'^create-shop/(?P<user_id>\d+)/$', views.create_shop, name='create'),
    url(r'^edit-shop/$', views.edit, name='edit'),
    url(r'^add-product/(?P<shop_id>\d+)/$', views.add_product, name='add_product'),
    
    # url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/(?P<username>[-\w]+)/$', views.detail, name='detail'),
    url(r'^post/(?P<id>\d+)/(?P<title>[-\w ]+)/', views.post_detail, name='post_text'),
    url(r'^(?P<product_id>\d+)/$', views.delete, name='delete'),
    url(r'^like/$', views.like, name='like'),
    url(r'^hate/$', views.hate, name='hate'),
    url(r'^post-like/$', views.post_like, name='post_like'),
    url(r'^post-hate/$', views.post_hate, name='post_hate'),
    url(r'^recommend/(?P<user_id>\d+)/(?P<product_id>\d+)/$', views.recommend, name='recommend'),
    url(r'update-stock/(?P<product_id>\d+)/', views.add_product_stock, name='stock'),
    url(r'^create-post/(?P<id>\d+)/$', views.create_post, name='post'),
    url(r'^share-product-link/(?P<id>\d+)/$', views.share_product, name='share_product'),
    # # url(r'^election/(?P<voter_id>\d+)/$', views.election, name='election'),
    # url(r'^kano/elections/(?P<voter_id>\d+)/$', views.election, name='kano_election'),
    # url(r'^kano/elections/(?P<voter_id>\d+)/(?P<governor_id>\d+)/$', views.election, name='kano_election_vote'),
    # url(r'^user-vote/$', views.elect, name='elect'),
    # #url(r'^(?P<business_name>[-\w]+)/', views.profile1, name='profile1'),
    
]

cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'


urlpatterns = [
    url(r'^cart-add/(?P<product_id>\d+)/$', views.cart_add, name='add'),
    url(r'^cart-remove/(?P<product_id>\d+)/$', views.cart_remove, name='remove'),
    url(r'^cart-detail/$', views.cart_detail, name='detail'),
    url(r'^home_cart_add/(?P<get_product_id>\d+)/$', views.home_add, name='home'),
]

estate/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf.urls.static import  static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('account.urls', namespace='account')),
    url(r'^bizz/', include('bizz.urls', namespace='bizz')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^chats/', include('chat.urls', namespace='chat')),
    url(r'^orders/', include('order.urls', namespace='order')),
    # path("paystack", include(('paystack.urls','paystack'),namespace='paystack')),
]



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.conf.urls import url
from . import views


app_name='order'

urlpatterns = [
    # url(r'^create/$', views.order_created, name='order_create'),
    url(r'^order/$', views.order_create, name='order_create'),
    url(r'^order-pay/(?P<id>\d+)/$', views.order_create, name='order_create_pay'),
    url(r'^buy/(?P<product_id>\d+)/$', views.buy, name='buy'),
    url(r'^order_pdf/(?P<order_id>\d+)/$', views.order_pdf, name='pdf'),
]

account/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile

class UserRegistrationForm(forms.ModelForm):

    GENDER = (
        ('male', 'Male'),
        ('female', 'Female'),
    )


    password = forms.CharField(label='Password',
                               widget=forms.PasswordInput)

    password2 = forms.CharField(label='Repeat password',
                                widget=forms.PasswordInput)
                                

    gender = forms.TypedChoiceField(choices=GENDER, coerce=str)


    class Meta:
        model = User
        fields = ('first_name', 'username', 'email')

        widgets = {
            'username':forms.TextInput(attrs={'placeholder':'No space and symbols, just text eg abdul, farida12, tosiFashion'}),
        }

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('The two passwords don\'t match')

        return cd['password2']

# form for editing user's info
class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class ProfileEditForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProfileEditForm, self).__init__(*args, **kwargs)
        self.fields['image'].required = True
        self.fields['phone'].required = True

    class Meta:
        model = Profile
        fields = ('image', 'phone')


class SearchForm(forms.Form):
    query = forms.CharField(label='Search for Properties', help_text='...')

class FriendSearchForm(forms.Form):
    search = forms.CharField(label='Search for friends')    

account/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import UserRegistrationForm, UserEditForm, ProfileEditForm, SearchForm, FriendSearchForm
from order.forms import OrderCreateForm
from bizz.forms import UpdateProductForm
from .tasks import account_created
from .models import Profile
from django.contrib import messages
from django.contrib.auth.models import User
from action.models import Action
from account.models import Contact
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from common.decorator import ajax_required
from bizz.models import Shop
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse
from bizz.models import Product
import redis
from django.conf import settings
from cart.forms import CartAddForm
from django.contrib.postgres.search import SearchQuery, SearchRank, SearchVector
from django.core.mail import send_mail
from order.models import Order
import random
from bizz.models import Post
from itertools import chain
import datetime
from django.contrib.postgres.search import TrigramSimilarity
from django.db.models.functions import Greatest
import numpy as np

from django.http import HttpResponse
from django.views.generic import View
from order.utils import render_to_pdf #created in step 4
from django.template.loader import get_template
from django.conf import settings
from io import BytesIO
from xhtml2pdf import pisa
from django.core.mail import send_mail, EmailMultiAlternatives, EmailMessage
from taggit.models import Tag

r = redis.StrictRedis(host=settings.REDIS_HOST,
                      port=settings.REDIS_PORT,
                      db=settings.REDIS_DB)




def stream(request):
    """Homepage"""

    # get all actions ordered by time of creation.
    actions = Action.objects.all()

    # get all the ids followed by the user in the current session
    if request.user.is_authenticated:
        user_following_ids = request.user.following.values_list('id', flat=True)

        # if the user follows anyone limit actions to those he follows only.
        # (in next version add actions_follow and actions to store actions of those you follow and those you dont)
        # (so as to allow the users access other people)
        if len(user_following_ids) > 2:
            actions = actions.filter(user_id__in=user_following_ids) \
                            .select_related('user', 'user__profile') \
                            .prefetch_related('target')

    # before it was 3
    paginator = Paginator(actions, 6)  # 15 actions/activities per page
    page = request.GET.get('page')  # get the page number

    try:
        actions = paginator.page(page)  # get he actions of a certain page

    except EmptyPage:
        if request.is_ajax():
            return HttpResponse('')  # return an empty http response so as to stop ajax from making additional requests

        actions = paginator.page(paginator.num_pages)  # stop at the last page

    except PageNotAnInteger:
        # return page 1

        actions = paginator.page(1)

    form = CartAddForm()  # render empty form.
    form_1 = OrderCreateForm()

    if request.is_ajax():
        return render(request,
                      'vinestream/stream_ajax.html',
                      {'actions': actions,
                       'section':'streams',
                       'form':form,
                       'form_1':form_1})

    # this will render for normal requests
    return render(request,'vinestream/stream.html',
                  {'section':'streams',
                   'actions':actions,
                   'form':form,
                   'form_1':form_1})


def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)  # prepopulate form with data.

        if form.is_valid():
            cd = form.cleaned_data
            new_user = form.save(commit=False)  # create instance of user but don't save yet.
            new_user.set_password(cd['password'])  # set user password
            new_user.gender = str(cd['gender'])  # set the user's gender
            new_user.save()  # save user in database
            # new user should follow himself
            Contact.objects.get_or_create(user_from=new_user, user_to=new_user)
            Contact.objects.get_or_create(user_from=new_user, user_to=User.objects.get(id=1))
            #account_created.delay(new_user.id)  # set asynchronous task in queue.
            # create profile for user
            Profile.objects.create(user=new_user)
            subject = 'Welcome to stardaf'
            message = 'Hello Dear!!, You have arrived at the first ultimate social commerce site in the world!\nWhere you can browse cool products and also set your business online\nThank you\n\nTeam StarDaf.'

            send_mail(subject, message, 'postmaster@stardaf.com', [new_user.email], fail_silently=False)
            # give a success notification.
            messages.success(request, 'Welcome {},'.format(new_user.get_full_name()))
            messages.success(request, 'use the credit card button to buy items',)

            # send new user to streams
            return redirect('account:login')
            # check from other platforms if users after creating an account login directly.

    else:
        form = UserRegistrationForm()

    return render(request,
                  'vinestream/register.html',
                  {'form':form})



def profile(request, username):

    # get the user
    try:
        user = User.objects.get(username=username)
    except User.DoesNotExist:
        return HttpResponse('<h1>No User has that Username!!!</h1>')    
    form = UpdateProductForm()

    try:
        shop = user.shop
        products = shop.products.all().order_by('-created')
        paginator = Paginator(products, 10)
        page = request.GET.get('page')

        try:
            products = paginator.page(page)

        except PageNotAnInteger:
            products = paginator.page(1)

        except EmptyPage:
            if request.is_ajax():
                return HttpResponse('')  # return an empty http response so as to stop ajax from making additional requests

            products = paginator.page(paginator.num_pages)  # stop at the last page

        if request.is_ajax():
            return render(request,
                      'vinestream/profile_ajax.html',
                      {'products': products,
                       'user':user,
                       'form':form})
                
    except Shop.DoesNotExist:
        products = None


    """profile will contain personal infomations such as images, names, small cards of products uploaded,
    history of uploads, chats,edit of info, bussiness location etc."""
    # total_views = r.incr('product:{}:views'.format(product.id))
    form_1 = OrderCreateForm()

    return render(request,
                  'vinestream/profile.html',
                  {'user':user,
                   'products':products,
                   'form':form,
                   'form_1':form_1})


@login_required
def profile1(request, business_name):
    try:
        shop = get_object_or_404(Shop, business_name=business_name)
        user = shop.owner
        products = shop.products.all().order_by('-created')
        
    except Shop.DoesNotExist:
        products = None

    form = UpdateProductForm()
    return render(request,
                  'vinestream/profile.html',
                  {'user':user,
                   'products':products,
                   'form':form})



# edit your account details
# will lead to a template having forms prepopulated with user's existing data
# which he can edit.
@login_required
def edit(request):

    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile, data=request.POST, files=request.FILES)
        # we user request.files because the form contains an image

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()  # save to database
            messages.success(request, 'Details updated successfully.')
            return redirect(request.user.get_absolute_url())

    else:
        # render form with user's pre-existing info.
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)

    return render(request,
                  'vinestream/edit.html',
                  {'user_form':user_form,
                   'profile_form':profile_form,
                   'section':'profile'})



@ajax_required
@require_POST
@login_required
def follow(request):
    user_id = request.POST.get('id')  # get user_id from ajax post
    action = request.POST.get('action')  # get data-action from ajax post

    try:
        user = get_object_or_404(User, id=user_id, is_active=True)  # get user from the database

        if action == 'follow':
            Contact.objects.get_or_create(user_from=request.user, user_to=user)  # request.user follows user

        else:
            Contact.objects.get(user_from=request.user, user_to=user).delete()  # not request.user follows user

        return JsonResponse({'status':'ok'})

    except User.DoesNotExist:
        return JsonResponse({'status':'ko'})



def market(request, tag_slug=None):
    # get all shops
    shops = Shop.objects.all()
    new_shops = Shop.objects.order_by('-created')[:20]

    # new code
    shops = Shop.objects.order_by('-created')[:5]
    products = sorted(Product.objects.filter(available=True), key=lambda x: random.random())
    posts = sorted(Post.objects.all(), key=lambda x: random.random())
    shops = sorted(Shop.objects.all(), key=lambda x: random.random())
    tag = None

    if tag_slug:

account/templates/vinestream/edit.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title %}
    Edit your profile
{% endblock %}

{% block content %}
    <br/>

    
    {% if user_form.errors or profile_form.errors %}
        {% for error in users_form.errors %}
            {{ error }}
        {% endfor %}
        {% for error in profile_form.errors %}
            {{ error }}
        {% endfor %}
    {% else %}

        

         <main role="main" class="container-fluid">
            <div class="offset-lg-3 col-lg-6 col-md-12">
              <div>
                <form action="." method="post" enctype="multipart/form-data">
                  <div class="mb-4 text-center">
                  <!-- <img src="{% static 'img/favicon.png' %}" alt="" width="72" height="72"> -->
                  <h1 class="h3 mb-3 font-weight-bold text-black-100 shadow-lg">Edit profile</h1>
                </div>
                  <div class="form-group">
                {% for field in user_form.visible_fields %}
                    <label id="field.id_for_label">{{ field.label }}</label>
                    {{ field|add_class:'form-control' }}
                {% endfor %}
                {% for field in profile_form.visible_fields %}
                    <label id="field.id_for_label">{{ field.label }}</label>
                    {{ field|add_class:'form-control' }}
                {% endfor %}
                {% csrf_token %}<br/>
                <input type="submit" value="edit account" class="btn btn-primary mx-auto d-block">
            </div>
                    </form>
            </div>
            </div><br/><br/> 
            </main>  

    {% endif %}

{% endblock %}

account/templates/vinestream/failure.html
{% extends 'base.html' %}

{% block title %}Transaction unsuccessful{% endblock %}


{% block content %}
    Transaction Failed
{% endblock %}

account/templates/vinestream/new_user_suggestions.html
{% load static %}
{% for shop in shops %}
        <a href='{{ shop.owner.get_absolute_url }}' style='text-decoration:none'>
                <div class='container-fluid' style='padding-left:22px'>
                        <div class="row">
                            <div class="col-xs-2">
                                <img src="{% if shop.logo %}{{ shop.logo.url }}
                        {% else %}{% static 'img/no_image.png'%}{% endif %}" style="border-radius:50%;width:50px; height:50px" class="img-circle">
                            </div>
                            <div class="col-xs-8">
                                        <strong>{{ shop.business_name }}</strong>
                                        <a href=''><i class='fa fa-check-circle'></i></a>
                                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                    &nbsp;&nbsp;&nbsp;&nbsp;

                                    <small class='text-muted float-right'>
                                        <a href='#' data-id="{{ shop.owner.id }}" 
                                        data-action="{% if request.user in shop.owner.followers.all %}un{% endif %}follow"
                                        class='follow' id='{{ shop.owner.id }}'>
                                        {% if not request.user in shop.owner.followers.all  %}
                                            <button class="btn btn-outline-primary btn-sm float-right">follow</button>
                                        {% else %}
                                            <button class="btn btn-outline-primary btn-sm float-right">unfollow</button>
                                        {% endif %}  
                                          
                                    </a>
                                    </small>
                                    
                            </div>
                        </div><hr width='70%' float='center' />
                </div>     </a><br/>      
    {% endfor %}
    <a href='{% url "account:stream" %}'><button class='btn btn-primary'>done</button></a>
    <br/><br/><br/>

account/templates/vinestream/new_users.html
{% load static %}

{% for user in me.following.all %} 
    {% if user.profile.image %}
        <a href='{{ user.get_absolute_url }}'><img src="{{ user.profile.image.url }}" style="height:50px; width:50px; border-radius:50%;"></a>
    {% else %}
         <a href='{{ user.get_absolute_url }}'><img src="{% static 'img/no_image.png' %}" style="height:50px; width:50px; border-radius:50%"></a>
    {% endif %}
{% empty %}
    You have no friends yet.    
{% endfor %}
<br/><br/><br/><br/><br/>

account/templates/vinestream/profile.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}


{% block title %}@{{ user.get_full_name }}{% endblock %}
{% block css %}
  <link rel="stylesheet" href="{% static 'css/profile.css' %}">
{% endblock %}

{% block content %}
<div style='position:fixed;right:25px;bottom:70px;z-index:10'>    
        <a href="https://wa.me/2347039071981?text=Hello customer support, Am having some issues.">
            <button class='btn btn-success' style='border-radius:50%'>
                <i class='fa fa-envelope-square'></i>
            </button>
        </a>
    </div>
        
    <!-- Custom styles for this template -->
    <!--<link href="starter-template.css" rel="stylesheet">-->
    <!--<link rel="stylesheet" type="text/css" href="signpage.css">-->

<body>

<hr>

<div class="container">
    
      <br>
     
  		{% comment %} <div class="col-sm-3"><!--left col-->


      <div class="text-center">
        <a href="{% url 'account:edit' %}"><img src="{% if user.profile.image %}{{ user.profile.image.url }}{% else %}{% static 'img/no_image.png'%}
        {% endif %}" class="avatar img-circle img-thumbnail" alt="avatar" style='width:100%; height:auto; border-radius:5px'></a>

      </div>


          <ul class="list-group">
            <li class="list-group-item text-muted">Activity <i class="fa fa-dashboard fa-1x"></i></li>
            {% if user.shop %}<li class="list-group-item text-right"><span class="pull-left"><strong>Uploaded </strong></span> {{ user.shop.products.count }}</li>{% endif %}
             <a href="{% url 'account:favourites' user.id %}" ><li class="list-group-item text-right"><span class="pull-left"><strong>Likes</strong></span> {{ user.product_liked.count }}</li></a>
            <a href='{% url "account:following" user.username %}'><li class="list-group-item text-right"><span class="pull-left"><strong>Following</strong></span> {{ user.following.count }}</li></a>
            <a href='{% url "account:followers" user.username %}'><li class="list-group-item text-right"><span class="pull-left"><strong>Followers</strong></span> {{ user.followers.count }}</li></a>
            {% if user.shop %}<li class="list-group-item text-right"><span class="pull-left"><strong>{{ user.shop.description|linebreaks }}</strong></li>{% endif %}

          </ul>

        </div><!--/col-3-->  {% endcomment %}

      <div class="container">
		<header>
			
			<div class="logocontainer">
                <div class="image-circle">
                    <img src="{% if user.profile.image %}{{ user.profile.image.url }}{% else %}{% static 'img/no_image.png'%}{% endif %}" alt="avatar" class="avatar"></div>
               
				<!--<div class="hover">
						<div><img src="asset/image/favicon%20-%20Copy.png"</div>
				</div>-->
			</div>
        </header>
        
            </div>

			</div> 

		
     
    </div>
       <div class="row"> 

    	<div class="col-sm-9 mx-auto d-block">
        <h1>{% if user.shop %}<span style='color:purple'>{{ user.shop.business_name }}</span>{% endif %}  {{ user.get_full_name }}</h1>
        <h2>@{{ user.username }}  </h2>
        {% if user != request.user %}
          <a href='#' data-id="{{ user.id }}" 
data-action="{% if request.user in user.followers.all %}unfollow{% else %}follow{% endif %}"
class='follow float-left' id='{{ user.id }}'>
{% if not request.user in user.followers.all  %}
    <button class="btn btn-outline-primary btn-sm float-right">follow</button>
{% else %}
    <button class="btn btn-outline-primary btn-sm float-right">unfollow</button>
{% endif %}    
</a>
        {% endif %}

          {% if request.user.id == user.shop.owner.id %}
            {% if user.shop %}
            <button class="btn btn-outline-danger float-right"><a href="{% url 'bizz:edit' %}">Edit Realtor info</a></button><br/>
              <button class="btn btn-lg  btn-block"><a href="{% url 'bizz:add_product' user.shop.id %}">Add Property</a></button>
              
            {% endif %}
          
          
          {% endif %}
          
          {% if user.shop %}
          
             
           
          <br/>
          <p class='text-muted float-left'>
            <i class='fa fa-map-marker'></i> {{ user.shop.business_address }} {{ user.shop.shop_address|linebreaks }}
          </p>
          {% endif %}

             {% if not user.shop %}
            {% if request.user == user %}
              <button class="btn btn-lg btn-dark btn-block"><a href="{% url 'bizz:create' user.id %}">Become an Agent</a></button> 
            {% endif %}
          {% endif %}   

          {% if request.user == user %}<a href="{% url 'account:logout_then_login' %}" class='float-right'><button class='btn btn-outline-primary btn-sm'>Sign-out</button></a>{% endif %}
          


          <br>
          <br>
          <!--<div class="card-group">-->

          <!--<div class="card-deck">-->
        <ul class="nav nav-tabs" id="myTab" role="tablist">
        {% if user.shop %}
          <li class="nav-item">
            <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true"><span class='fa fa-hashtag'></span></a>
          </li>
        {% endif %}  
        {% if request.user == user %}
          <li class="nav-item">
            <a class="nav-link"  href="{% url 'account:edit' %}" ><span class='fa fa-cog'></span></a>
          </li>{% endif %}
          <li class="nav-item">
            <a class="nav-link" id="like-tab" href="{% url 'account:favourites' user.id %}" ><span class='fa fa-heart'></span></a>
          </li>
          
          {% if user.profile.phone %}
            <li class="nav-item">
              <a class='nav-link' href="https://wa.me/234{{ user.profile.phone }}?text=Hey {{ user.username }}, Nice meeting you on stardaf :-)" style='color:green'><span class='fa fa-whatsapp'></a>
            </li>  
          {% endif %}
          
          
          <li class="nav-item">
            <a class="nav-link" id="like-tab"><span class='fa fa-share-alt' data-toggle="modal" data-target='#exampleModalCenter_{{ user.id }}'></span></a>
          </li>
          <div class="modal fade" id="exampleModalCenter_{{ user.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Share to friends</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
                    <!-- AddToAny BEGIN -->
            <div class="a2a_kit a2a_kit_size_32 a2a_default_style">
            <a class="a2a_dd" href="https://www.addtoany.com/share"></a>
            <a class="a2a_button_facebook"></a>
            <a class="a2a_button_twitter"></a>
            <a class="a2a_button_google_gmail"></a>
            <a class="a2a_button_whatsapp"></a>
            <a class="a2a_button_sms"></a>
            </div>
            <script async src="https://static.addtoany.com/menu/page.js"></script>
            <!-- AddToAny END -->
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        
      </div>
    </div>
  </div>
</div>
{% comment %} {% if user.id == 1 %}
  <button class='btn btn-danger'><a href='{% url 'account:delete' user.id %}'>update</a></button>
{% endif %} {% endcomment %}
          <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
            {% if user.shop %}
                    <div class="row" id='profile_stream'>
                    {% include 'vinestream/profile_ajax.html' %}
                </div>
            {% endif %}    
            </div>

            
          </div>

        </ul>

          <!--</div>-->
        <br/><br/><br/>
{% endblock %}

{% block domready %}


    var page = 1;
    var block_request = false;
    var empty_page = false;

    $(window).scroll(function() {

        var margin = $(document).height() - $(window).height() - 500;

         if ($(window).scrollTop() > margin && block_request == false && empty_page == false) {
             block_request = true;
             page += 1;

             $.get('?page=' + page, function(data) {
                 if (data == '') {
                     empty_page = true;
                 }
                 else {
                     block_request = false;
                     $('#profile_stream').append(data);
                 }
             })
         }
    });


  
{% endblock %}

account/templates/vinestream/users_comment.html
{% load static %}

{% for comment in all_comments %}
    {% if comment.user.profile.image %}
        <img src="{{ comment.user.profile.image.url }}" style="height:20px; width:20px; border-radius:50%">
    {% else %}
         <img src="{% static 'img/no_image.png' %}" style="height:20px; width:20px; border-radius:50%">
    {% endif %}

{% endfor %}