bizz/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name='bizz'

urlpatterns = [
    url(r'^create-shop/(?P<user_id>\d+)/$', views.create_shop, name='create'),
    url(r'^edit-shop/$', views.edit, name='edit'),
    url(r'^add-product/(?P<shop_id>\d+)/$', views.add_product, name='add_product'),
    
    # url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/(?P<username>[-\w]+)/$', views.detail, name='detail'),
    url(r'^post/(?P<id>\d+)/(?P<title>[-\w ]+)/', views.post_detail, name='post_text'),
    url(r'^(?P<product_id>\d+)/$', views.delete, name='delete'),
    url(r'^like/$', views.like, name='like'),
    url(r'^hate/$', views.hate, name='hate'),
    url(r'^post-like/$', views.post_like, name='post_like'),
    url(r'^post-hate/$', views.post_hate, name='post_hate'),
    url(r'^recommend/(?P<user_id>\d+)/(?P<product_id>\d+)/$', views.recommend, name='recommend'),
    url(r'update-stock/(?P<product_id>\d+)/', views.add_product_stock, name='stock'),
    url(r'^create-post/(?P<id>\d+)/$', views.create_post, name='post'),
    url(r'^share-product-link/(?P<id>\d+)/$', views.share_product, name='share_product'),
    # # url(r'^election/(?P<voter_id>\d+)/$', views.election, name='election'),
    # url(r'^kano/elections/(?P<voter_id>\d+)/$', views.election, name='kano_election'),
    # url(r'^kano/elections/(?P<voter_id>\d+)/(?P<governor_id>\d+)/$', views.election, name='kano_election_vote'),
    # url(r'^user-vote/$', views.elect, name='elect'),
    # #url(r'^(?P<business_name>[-\w]+)/', views.profile1, name='profile1'),
    
]

chat/urls.py
from django.conf.urls import url
from . import views

app_name='chat'


urlpatterns = [
    url('^mychats/$', views.chats, name='chats'),
    url('^chat/(?P<username>[-\w]+)/$', views.thread, name='thread'),
]

#url('^chat/(?P<username>[-\w]+)/(?P<product_id>\d+)/$', views.thread, name='thread'),

estate/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf.urls.static import  static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('account.urls', namespace='account')),
    url(r'^bizz/', include('bizz.urls', namespace='bizz')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^chats/', include('chat.urls', namespace='chat')),
    url(r'^orders/', include('order.urls', namespace='order')),
    # path("paystack", include(('paystack.urls','paystack'),namespace='paystack')),
]



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/models.py
from django.db import models
from django.conf import settings
from django.db.models import Q


class ThreadManager(models.Manager):
    def by_user(self, user):
        qlookup = Q(first=user) | Q(second=user)
        qlookup2 = Q(first=user) & Q(second=user)
        qs = self.get_queryset().filter(qlookup).exclude(qlookup2).distinct()
        return qs

    def get_or_new(self, user, other_username): # get_or_create
        username = user.username
        if username == other_username:
            return None
        qlookup1 = Q(first__username=username) & Q(second__username=other_username)
        qlookup2 = Q(first__username=other_username) & Q(second__username=username)
        qs = self.get_queryset().filter(qlookup1 | qlookup2).distinct()
        if qs.count() == 1:
            return qs.first(), False
        elif qs.count() > 1:
            return qs.order_by('timestamp').first(), False
        else:
            Klass = user.__class__
            user2 = Klass.objects.get(username=other_username)
            if user != user2:
                obj = self.model(
                        first=user,
                        second=user2
                    )
                obj.save()
                return obj, True
            return None, False


class Thread(models.Model):
    first        = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_first')
    second       = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_second')
    updated      = models.DateTimeField(auto_now=True)
    timestamp    = models.DateTimeField(auto_now_add=True)

    objects      = ThreadManager()

    @property
    def room_group_name(self):
        return f'chat_{self.id}'

    def broadcast(self, msg=None):
        if msg is not None:
            broadcast_msg_to_chat(msg, group_name=self.room_group_name, user='admin')
            return True
        return False


class ChatMessage(models.Model):
    thread      = models.ForeignKey(Thread, related_name='chat_messages', null=True, blank=True, on_delete=models.SET_NULL)  # thread.chat_messages.all
    user        = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='sender', on_delete=models.CASCADE)
    message     = models.TextField(blank=True)
    timestamp   = models.DateTimeField(auto_now_add=True)

chat/forms.py
from django import forms
from .models import ChatMessage

class ComposeForm(forms.Form):
    message = forms.CharField(
            widget=forms.TextInput(
                attrs={"class": "form-control"}
                )
            )


class ChatForm(forms.ModelForm):
    class Meta:
        model = ChatMessage
        fields = ('message',)

        

chat/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Thread
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .forms import ChatForm
from .models import ChatMessage
from bizz.models import Product


@login_required
def thread(request, username):
    user = request.user  # get the current user in the request context.
    #product = get_object_or_404(Product, id=product_id)
    other_user = User.objects.get(username=username)  # get the other user
    thread = Thread.objects.get_or_new(user, other_user)[0]  # get_or_create thread between users.
    # this is returning None.
    form = ChatForm()


    if request.method == 'POST':
        message = request.POST.get('message')

        
        # create chat message instance but don't save to the database yet.
        new_chat = ChatMessage.objects.create(thread=thread, user=user, message=message)
        new_chat.save()  # save to database.
        return render(request,
                'chats/thread.html',
                {'thread':thread,
                'user':user,
                'form':form,
                'other_user':other_user})

    else:
        form = ChatForm()  # send empty chat form to the template.
        
    return render(request,
        'chats/thread.html',
        {'thread':thread,
        'user':user,
        'form':form,
        'other_user':other_user})

      


@login_required
def chats(request):
    user = request.user
    threads = list(Thread.objects.filter(first=user)) + list(Thread.objects.filter(second=user))
    return render(request,
    'chats/mychats.html',
    {'user':user,
    'threads':threads})

chat/templates/chats/mychats.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    my chats
{% endblock %}

{% block content %}
    <div style='position:fixed;right:25px;bottom:70px;z-index:10'>    
        <a href='{% url 'chat:chats' %}'>
            <button class='btn btn-success' style='border-radius:50%'>
                <i class='fa fa-align-right'></i>
            </button>
        </a>
    </div>
    <br/>
    {% for thread in threads %}
        {% with other_user=thread.second %}
        {% with first_user=thread.first %}
        <a href='{% if user == thread.first %}{% url "chat:thread" other_user.username %}{% else %}
        {% url "chat:thread" first_user.username  %}{% endif %}' style='text-decoration:none'>
                <div class='container-fluid' style='padding-left:22px'>
                        <div class="row">
                            <div class="col-xs-2">
                            {% if user == thread.first %}
                                <img src="{%  if other_user.profile.image %}{{ other_user.profile.image.url }}
                        {% else %}{% static 'img/no_image.png'%}{% endif %}" style="border-radius:50%;width:50px; height:50px" class="img-circle">
                            {% else %}
                                <img src="{%  if first_user.profile.image %}{{ first_user.profile.image.url }}
                        {% else %}{% static 'img/no_image.png'%}{% endif %}" style="border-radius:50%;width:50px; height:50px" class="img-circle">
                            {% endif %}
                            </div>
                            <div class="col-xs-8">&nbsp;&nbsp;&nbsp;&nbsp;
                                    {% if user == thread.first %}
                                        <strong style='vertical-align:baseline'>{{ other_user.username }}</strong>
                                    {% else %}
                                    <strong style='vertical-align:baseline'>{{ first_user.username }}</strong>
                                    {% endif %}<br/>
                                    <small class='text-muted' style='vertical-align:text-bottom; padding-left:22px'>{{ thread.chat_messages.last.message|truncatewords:5 }}</small>
                                    
                            </div>
                        </div><hr width='70%' float='center' />
                </div>     </a>
            {% endwith %}
        {% endwith %}
        {% empty %}
            <h2><p style='padding:50px' class='text-muted'>You have no chats yet</p></h2>
    {% endfor %}
{% endblock %}

chat/templates/chats/thread.html
{% extends "base.html" %}
{% load static %}



{% block title %}{{ user.username }}/{{ other_user.username }}{% endblock %}

{% block style %}href="{% static "css/chatcom.css" %}"{% endblock %}

{% block content %}
    <br/>
    
    <div style='height:60px;z-index:10000000; position:fixed;top:0px;right:0px;left:0px;background-color:green;vertical-align:baseline'>
    {% comment %} <h3>Thread for {% if user == thread.first %}{{ other_user.username }}{% else %}{{ user.username }}{% endif %}</h3> {% endcomment %}
    &nbsp;
    {% if request.user == user %}
        
            <a href='{{ other_user.get_absolute_url }}'>
                {% if other_user.profile.image %}
                    <img src='{{ other_user.profile.image.url }}' style='border-radius:50%; height:50px;width:50px;vertical-align:baseline'/>
                {% else %}
                    <img src='{% static "img/no_image.png" %}' style='border-radius:50%; height:50px;width:50px;vertical-align:baseline' />
                {% endif %}    
            </a>
            {% if other_user.shop %}
                    <div class='float-right'>
                    <div class="dropdown">
                        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            seller info
                        </a>

                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            <a class="dropdown-item" href="#">{{ other_user.shop.business_name }}</a>
                            <a class="dropdown-item" href="#">0{{ other_user.profile.phone }}</a>
                            <a class="dropdown-item" href="#">{{ other_user.shop.business_address }}</a>
                            <a class="dropdown-item" href="#">{{ other_user.shop.shop_address }}</a>
                        </div>
                    </div>
                    </div>
            {% else %}
                <em style='vertical-align:baseline;font-size:large'>{{ user.first_name }}</em>
            {% endif %}

    {% else %}    
        <a href='{{ user.get_absolute_url }}'>
            {% if user.profile.image %}
                <img src='{{ user.profile.image.url }}' style='border-radius:50%; height:50px;width:50px;vertical-align:baseline'/>
            {% else %}
                <img src='{% static "img/no_image.png" %}' style='border-radius:50%; height:50px;width:50px;vertical-align:baseline' />
            {% endif %}    
        </a>
    {% endif %}
    </div>

    <div class='chat'>
        <section>
            <ul id='chat-items'>
                <br/><br/>
                {% for chat in thread.chat_messages.all %}

                    {% if chat.user == user %}
                        <li class="seller">
                            <div class="date">
                                {{ chat.timestamp|timesince }} ago
                            </div>
                            <div class="message">
                            <p>
                                    {{ chat.message }}
                            </p>
                            </div>
                        </li>
                    {% else %}
                            <li class="buyer">
                            <div class="date">
                                {{ chat.timestamp|timesince }}
                            </div>
                            <div class="message">
                            <p>
                                {{ chat.message }}
                            </p>
                            </div>
                        </li>
                    {% endif %}<br/>

                {% endfor %}

            </ul>
           
         

<form id='form' method='post' action='.'> 
    {% comment %} {{ form.as_p }}
    <input type='hidden' id='myUsername' value='{{ user.username }}' />
    {% csrf_token %}
    <input type='submit' class='btn btn-primary'/> {% endcomment %}
    <input type='hidden' id='myUsername' value='{{ user.username }}' />
            <div class="type_msg">
                <div class="input_msg_write">
                    <textarea class="write_msg" placeholder="Type a message" cols='35' name='message' id='id_message'/></textarea>
                    {% csrf_token %}
                  <button type='submit' class="msg_send_btn" type="button"><i class="fa fa-location-arrow"></i></span></button>
                </div>
              </div>
    
</form><br/>
 </section>    
    </div>  

{% endblock %}


{% block domready %}

    $('#id_message').focus();
    var protocol = 'ws://'
    var formData = $('#form');
    var msgInput = $('#id_message');
    var chatHolder = $('#chat-items');
    var me = $('#myUsername').val()

    if (window.location.protocol == 'https:') {
        protocol = 'wss://'
    }

    var endpoint = protocol + window.location.host + window.location.pathname;

    var socket = new WebSocket(endpoint)

    socket.onmessage = function(e) {
        console.log('message', e)
        var chatMsg = JSON.parse(e.data)
        var link = chatMsg.message
        if (me == chatMsg.username) { 
                if (chatMsg.message.startsWith('www'))
                    chatHolder.append('<li class="seller">' +
                    '<div class="date">' + 
                            chatMsg.timestamp
                    + '</div>' +
                        '<div class="message">' +
                            '<p>' + 
                                '<a class="link">' + link + '</a>' 
                            +  '</p>'
                        + '</div>'
                    + '</li>')
                else if (chatMsg.message.startsWith('https'))
                    chatHolder.append('<li class="seller">' +
                    '<div class="date">' + 
                            chatMsg.timestamp
                    + '</div>' +
                        '<div class="message">' +
                            '<p>' + 
                                '<a class="link">' + link + '</a>' 
                            +  '</p>'
                        + '</div>'
                    + '</li>')       
                else
                    chatHolder.append('<li class="seller">' +
                    '<div class="date">' + 
                            chatMsg.timestamp
                    + '</div>' +
                        '<div class="message">' +
                            '<p>' + 
                                chatMsg.message 
                            +  '</p>'
                        + '</div>'
                    + '</li>')    
            
        }
        $('.link').attr('href', link)
    }    

    socket.onopen  = function(e) {
        console.log('open', e)
        formData.submit(function(event){
            event.preventDefault();
            var msgText = msgInput.val();
            var finalData = {
                'message':msgText
            }
            socket.send(JSON.stringify(finalData))
            formData[0].reset()
        })
    }
    socket.onclose  = function(e) {
        console.log('close', e)
    }
    socket.onerror  = function(e) {
        console.log('error', e) 
    }
{% endblock %}