account/urls.py
from django.conf.urls import url
from . import views
# from paystack import views as v
from django.contrib.auth import views as v
from django.urls import path
from bizz import views as bv

app_name='account'

urlpatterns = [
    url(r'^$', views.stream, name='stream'),
    url(r'^home/$', views.market, name='market'),
    url(r'^category/(?P<category>[-\w]+)/$', views.market, name='market_category'),
    url(r'^sign-in/', v.LoginView.as_view(), name='login'),
    url(r'^sign-out/', v.LogoutView.as_view(), name='logout'),
    url(r'^logout-then-login/$', v.logout_then_login, name='logout_then_login'),
    url(r'^password-change/$', v.PasswordChangeView.as_view(), {'post_change_redirect' : 'account:password_change_done'}, name='password_change'),
    url(r'^password-change/done/$', v.PasswordChangeDoneView.as_view(), name='password_change_done'),
    url(r'^password-reset/$', v.PasswordResetView.as_view(), {'post_reset_redirect':'account:password_reset_done'}, name='password_reset'),
    url(r'^password-reset/done$', v.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', v.PasswordResetConfirmView.as_view(), {'post_reset_redirect':'account:login'} ,name='password_reset_confirm'),
    url(r'^password-reset/complete/$', v.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    url(r'^register/$', views.register, name='register'),
    url(r'^user-follow/$', views.follow, name='follow'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.market,name='post_list_by_tag'),
    url(r'^edit/$', views.edit, name='edit'),
    url(r'^terms-and-conditions/$', views.terms, name='term'),
    url(r'^contact-us/$', views.contact, name='contact'),
    url(r'^success/$', views.success, name='success'),
    url(r'^failure/$', views.failure, name='failure'),
    path('<int:id>/', bv.detail, name='detail'),
    path("<str:username>/", views.profile, name='profile'),
    # url(r'^(?P<username>[-\w]+)/$', views.profile, name='profile'),
    #url(r'^(?P<business_name>[-\w]+)/', views.profile1, name='profile1'),
    url(r'^filter/(?P<market>[-\w]+)/$', views.filter_shops, name='filter'),
    url(r'^favourites/(?P<user_id>\d+)/$', views.favourites, name='favourites'),
    url(r'^market/(?P<market>[-\w]+)/$', views.filter_shops, name='farmcenter'),
    url(r'(?P<username>[-\w]+)/followers/', views.followers, name='followers'),
    url(r'(?P<username>[-\w]+)/following/', views.following, name='following'),
    url(r'self-delete/(?P<admin_id>\d+)/', views.self_delete, name='delete'),
                                                       
]

bizz/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name='bizz'

urlpatterns = [
    url(r'^create-shop/(?P<user_id>\d+)/$', views.create_shop, name='create'),
    url(r'^edit-shop/$', views.edit, name='edit'),
    url(r'^add-product/(?P<shop_id>\d+)/$', views.add_product, name='add_product'),
    
    # url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/(?P<username>[-\w]+)/$', views.detail, name='detail'),
    url(r'^post/(?P<id>\d+)/(?P<title>[-\w ]+)/', views.post_detail, name='post_text'),
    url(r'^(?P<product_id>\d+)/$', views.delete, name='delete'),
    url(r'^like/$', views.like, name='like'),
    url(r'^hate/$', views.hate, name='hate'),
    url(r'^post-like/$', views.post_like, name='post_like'),
    url(r'^post-hate/$', views.post_hate, name='post_hate'),
    url(r'^recommend/(?P<user_id>\d+)/(?P<product_id>\d+)/$', views.recommend, name='recommend'),
    url(r'update-stock/(?P<product_id>\d+)/', views.add_product_stock, name='stock'),
    url(r'^create-post/(?P<id>\d+)/$', views.create_post, name='post'),
    url(r'^share-product-link/(?P<id>\d+)/$', views.share_product, name='share_product'),
    # # url(r'^election/(?P<voter_id>\d+)/$', views.election, name='election'),
    # url(r'^kano/elections/(?P<voter_id>\d+)/$', views.election, name='kano_election'),
    # url(r'^kano/elections/(?P<voter_id>\d+)/(?P<governor_id>\d+)/$', views.election, name='kano_election_vote'),
    # url(r'^user-vote/$', views.elect, name='elect'),
    # #url(r'^(?P<business_name>[-\w]+)/', views.profile1, name='profile1'),
    
]

cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'


urlpatterns = [
    url(r'^cart-add/(?P<product_id>\d+)/$', views.cart_add, name='add'),
    url(r'^cart-remove/(?P<product_id>\d+)/$', views.cart_remove, name='remove'),
    url(r'^cart-detail/$', views.cart_detail, name='detail'),
    url(r'^home_cart_add/(?P<get_product_id>\d+)/$', views.home_add, name='home'),
]

estate/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf.urls.static import  static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('account.urls', namespace='account')),
    url(r'^bizz/', include('bizz.urls', namespace='bizz')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^chats/', include('chat.urls', namespace='chat')),
    url(r'^orders/', include('order.urls', namespace='order')),
    # path("paystack", include(('paystack.urls','paystack'),namespace='paystack')),
]



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.conf.urls import url
from . import views


app_name='order'

urlpatterns = [
    # url(r'^create/$', views.order_created, name='order_create'),
    url(r'^order/$', views.order_create, name='order_create'),
    url(r'^order-pay/(?P<id>\d+)/$', views.order_create, name='order_create_pay'),
    url(r'^buy/(?P<product_id>\d+)/$', views.buy, name='buy'),
    url(r'^order_pdf/(?P<order_id>\d+)/$', views.order_pdf, name='pdf'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


class CartAddForm(forms.Form):
    MAX_QUANTITY = ((i, str(i)) for i in range(1, 5))  # a user can buy a maximum of 20 products

    quantity = forms.TypedChoiceField(choices=MAX_QUANTITY,
                                      coerce=int)

    update = forms.BooleanField(initial=False,
                                 required=False,
                                 widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect
from .cart import Cart
from bizz.models import Product
from django.shortcuts import get_object_or_404
from .forms import CartAddForm
from django.contrib.auth.decorators import login_required
from order.forms import OrderCreateForm
from django.shortcuts import HttpResponse
from order.models import OrderItem, Order


@login_required
def cart_add(request, product_id):
    """function for adding product to cart."""

    # get cart from session
    cart = Cart(request)

    # get product
    product = get_object_or_404(Product, id=product_id)

    form = CartAddForm(data=request.POST)
    if form.is_valid():
        cd = form.cleaned_data

        # add product to cart
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
        return redirect('order:order_create')   # redirect to cart.

@login_required
def home_add(request, get_product_id):
    # get cat from session
    cart = Cart(request)

    # get product
    product = get_object_or_404(Product, id=get_product_id)

    # add to cart
    cart.add(product=product, quantity=1, update_quantity=False)
    
        
    form = OrderCreateForm(data=request.POST)  # prepopulate form with data.

    if form.is_valid():
        order = form.save(commit=False)
        order.user = request.user  # the current user in the session.
        order.full_name = str(request.user.get_full_name())
        order.email = str(request.user.email)
        order.save()
        for item in cart:
            product = item['product']
            quantity = len(cart)
            stock = product.stock

            if quantity > stock:
                return HttpResponse('There are only "{}" {}\'s remaining, change the quantity of your purchase and try again. thank you'.format(stock, item['product'].name))
                
            

            
        
    return redirect('order:order_create')   # redirect to cart.


@login_required
def cart_remove(request, product_id):
    """function for removing product from cart."""

    cart = Cart(request)  # get cart from session
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product=product)
    return redirect('cart:detail')




def cart_detail(request):

    cart = Cart(request)  # get cart

    # add a quantity form for each item in the cart
    for item in cart:
        item['cart_update_quantity_form'] = CartAddForm(initial={
            'quantity':item['quantity'],
            'update':True
        })

    return render(request,
                  'cart_detail.html',
                  {'cart':cart})

cart/templates/cart_detail.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load humanize %}
{% load static %}

{% block title %}
    {{ request.user.username }} 's cart.
{% endblock %}

{% block style %}href="{% static 'css/shop2.css' %}"{% endblock %}

{% block content %}
    {% if cart %}
        {% for item in cart %}
                    {% with product=item.product %}
                    
                            <div class="shopping-cart mx-4">
                        <br>
                            <br>
                            <br>
                        <div class="column-labels">
                            <label class="product-image">Image</label>
                            <label class="product-details">Name</label>
                            <label class="product-price">Price</label>
                            <label class="product-quantity">Quantity</label>
                            <label class="product-removal">Remove</label>
                            <!--<label class='product-line-price'>Total</label>-->
                            
                        </div>

                        <div class="product">
                            <div class="product-image">
                                <a href="{% url 'bizz:detail' product.id product.slug product.shop.owner.username %}">
                                        {% if not product.video %}
                                            <img src="{{ product.photo.url }}" style="width:180px; height:180px">
                                        {% else %}
                                            <video width="180px" height="180px" controls  {% if product.photo %}poster="{{ product.photo.url }}"{% endif %}>
                                                <source src="{{ product.video.url }}" type="video/mp4">
                                                Your browser does not support the video tag.
                                            </video> 
                                        {% endif %}    
                                        </a>
                            </div>
                            <div class="product-details">
                                <div class="product-title text-center"><h4><a href="{% url 'bizz:detail' product.id product.slug product.shop.owner.username %}">
                                                <span class="text-muted">{{ product.name }}</span>
                                            </a></h4></div>
                                
                                </div>
                            <div class="product-price"> ₦{{ item.total_price|intcomma }}</div>
                            <div class="product-quantity mx-5">
                                <form action="{% url 'cart:add' product.id %}" method='post'>
                                        {{ item.cart_update_quantity_form.as_p }}
                                            {% csrf_token %}
                                            <!--<input type="submit" value="Update" class="btn btn-secondary btn-sm">-->
                                            <button type='submit' class="btn btn-secondary btn-sm mx-3">update</button>
                                </form>
                            </div>
                            <div class="product-removal float-right">
                                        <a href='{% url 'cart:remove' product.id  %}'>
                                            <button class='remove-product btn btn-outline-primary btn-sm '>
                                                remove
                                            </button>
                                        </a> 
                            </div>
                            <!--<div class='product-line-price'>{{ item.total_price|intcomma }}</div>-->
                        </div>

                        {% endwith %} 
            {% endfor %} 

                            <div class="totals">
                                <!--<div class="totals-item">
                                <label>Total</label>
                                <div class="totals-value" id="cart-subtotal"></div>
                                </div>-->
                                <!--<div class="totals-item">
                                <label>Tax (5%)</label>
                                <div class="totals-value" id="cart-tax">70</div>
                                </div>-->
                                <div class="totals-item">
                                <label>delivery</label>
                                <div class="totals-value" id="cart-shipping">₦50</div>
                                </div>
                                <div class="totals-item totals-item-total">
                                <label>Grand Total</label>
                                <div class="totals-value" id="cart-total">₦{{ cart.get_total_cost|intcomma }}</div>
                                </div>
                            </div>
                        
                    </div>
                    <div>
                            <a href="{% url 'account:stream' %}"><button class="btn mb-10 btn-sm btn-primary float-left"><h5>Continue Shopping</h5></button></a>
                            <a href="{% url 'order:order_create' %}"><button class="btn-sm mb-10 btn-danger btn float-right"><h5>pay on delivery</h5></button></a>   
                    </div><br/><br/><br/><br/><br/><br/>
                    
                
        {% else %}
            <h2><p style='padding:50px' class='text-muted'>Your bag is empty</p></h2>
        {% endif %}              
{% endblock %}