account/urls.py
from django.conf.urls import url
from . import views
# from paystack import views as v
from django.contrib.auth import views as v
from django.urls import path
from bizz import views as bv

app_name='account'

urlpatterns = [
    url(r'^$', views.stream, name='stream'),
    url(r'^home/$', views.market, name='market'),
    url(r'^category/(?P<category>[-\w]+)/$', views.market, name='market_category'),
    url(r'^sign-in/', v.LoginView.as_view(), name='login'),
    url(r'^sign-out/', v.LogoutView.as_view(), name='logout'),
    url(r'^logout-then-login/$', v.logout_then_login, name='logout_then_login'),
    url(r'^password-change/$', v.PasswordChangeView.as_view(), {'post_change_redirect' : 'account:password_change_done'}, name='password_change'),
    url(r'^password-change/done/$', v.PasswordChangeDoneView.as_view(), name='password_change_done'),
    url(r'^password-reset/$', v.PasswordResetView.as_view(), {'post_reset_redirect':'account:password_reset_done'}, name='password_reset'),
    url(r'^password-reset/done$', v.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', v.PasswordResetConfirmView.as_view(), {'post_reset_redirect':'account:login'} ,name='password_reset_confirm'),
    url(r'^password-reset/complete/$', v.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    url(r'^register/$', views.register, name='register'),
    url(r'^user-follow/$', views.follow, name='follow'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.market,name='post_list_by_tag'),
    url(r'^edit/$', views.edit, name='edit'),
    url(r'^terms-and-conditions/$', views.terms, name='term'),
    url(r'^contact-us/$', views.contact, name='contact'),
    url(r'^success/$', views.success, name='success'),
    url(r'^failure/$', views.failure, name='failure'),
    path('<int:id>/', bv.detail, name='detail'),
    path("<str:username>/", views.profile, name='profile'),
    # url(r'^(?P<username>[-\w]+)/$', views.profile, name='profile'),
    #url(r'^(?P<business_name>[-\w]+)/', views.profile1, name='profile1'),
    url(r'^filter/(?P<market>[-\w]+)/$', views.filter_shops, name='filter'),
    url(r'^favourites/(?P<user_id>\d+)/$', views.favourites, name='favourites'),
    url(r'^market/(?P<market>[-\w]+)/$', views.filter_shops, name='farmcenter'),
    url(r'(?P<username>[-\w]+)/followers/', views.followers, name='followers'),
    url(r'(?P<username>[-\w]+)/following/', views.following, name='following'),
    url(r'self-delete/(?P<admin_id>\d+)/', views.self_delete, name='delete'),
                                                       
]

bizz/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name='bizz'

urlpatterns = [
    url(r'^create-shop/(?P<user_id>\d+)/$', views.create_shop, name='create'),
    url(r'^edit-shop/$', views.edit, name='edit'),
    url(r'^add-product/(?P<shop_id>\d+)/$', views.add_product, name='add_product'),
    
    # url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/(?P<username>[-\w]+)/$', views.detail, name='detail'),
    url(r'^post/(?P<id>\d+)/(?P<title>[-\w ]+)/', views.post_detail, name='post_text'),
    url(r'^(?P<product_id>\d+)/$', views.delete, name='delete'),
    url(r'^like/$', views.like, name='like'),
    url(r'^hate/$', views.hate, name='hate'),
    url(r'^post-like/$', views.post_like, name='post_like'),
    url(r'^post-hate/$', views.post_hate, name='post_hate'),
    url(r'^recommend/(?P<user_id>\d+)/(?P<product_id>\d+)/$', views.recommend, name='recommend'),
    url(r'update-stock/(?P<product_id>\d+)/', views.add_product_stock, name='stock'),
    url(r'^create-post/(?P<id>\d+)/$', views.create_post, name='post'),
    url(r'^share-product-link/(?P<id>\d+)/$', views.share_product, name='share_product'),
    # # url(r'^election/(?P<voter_id>\d+)/$', views.election, name='election'),
    # url(r'^kano/elections/(?P<voter_id>\d+)/$', views.election, name='kano_election'),
    # url(r'^kano/elections/(?P<voter_id>\d+)/(?P<governor_id>\d+)/$', views.election, name='kano_election_vote'),
    # url(r'^user-vote/$', views.elect, name='elect'),
    # #url(r'^(?P<business_name>[-\w]+)/', views.profile1, name='profile1'),
    
]

estate/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf.urls.static import  static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('account.urls', namespace='account')),
    url(r'^bizz/', include('bizz.urls', namespace='bizz')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^chats/', include('chat.urls', namespace='chat')),
    url(r'^orders/', include('order.urls', namespace='order')),
    # path("paystack", include(('paystack.urls','paystack'),namespace='paystack')),
]



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bizz/views.py
from django.shortcuts import render, redirect
from .forms import CreateShopForm, ShopEditForm, AddProductForm, UpdateProductForm
from .tasks import shop_created
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .models import Shop, Product
from cart.forms import CartAddForm
from django.conf import settings
import redis
from Comment.forms import CommentForm
from action.action import create_action
from common.decorator import ajax_required
from django.views.decorators.http import require_POST
from django.http import JsonResponse
from django.db.models import Count
from action.models import Action
from .forms import AddPostForm
from order.forms import OrderCreateForm
from bizz.models import Post, Governor
import random
from django.http import HttpResponse
from .preprocessors import AspectAwarePreprocessor
from PIL import Image
import numpy as np
import os
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# initializing

# connect to redis.
r = redis.StrictRedis(host=settings.REDIS_HOST, port=settings.REDIS_PORT, db=settings.REDIS_DB)


@login_required
def create_shop(request, user_id):
    user = get_object_or_404(User, id=user_id, is_active=True)

    if request.method == 'POST':
        form = CreateShopForm(data=request.POST, files=request.FILES)  # prepopulate form with data.
        if form.is_valid():
            new_shop = form.save(commit=False)  # create instance of user but don't save to db yet.
            new_shop.owner = request.user
            new_shop.save()  # save to database
            # shop_created.delay(new_shop.id)  # add asynchronous tasks to queue
            messages.success(request, 'Congratulations {}, You can add products to your brand through your profile {}' \
                             .format(new_shop.owner.username, new_shop.owner.get_absolute_url()))

            # return user to his profile where he will now have a add product link
            
            return redirect(new_shop.owner.get_absolute_url())

    else:
        form = CreateShopForm()
        messages.success(request, 'You will be further authenticated by our team. Creating a company is free')

    return render(request,
                  'add_shop.html',
                  {'form':form,
                   'user':user})

@login_required
def edit(request):
    if request.method == 'POST':
        form = ShopEditForm(instance=request.user.shop, data=request.POST, files=request.FILES)
        if form.is_valid():
            shop = form.save(commit=False)
            shop.owner = request.user
            shop.save()

            messages.success(request, 'You have successfully updated your shop ;-)')
            return redirect(shop.owner.get_absolute_url())

    else:
        form = ShopEditForm(instance=request.user.shop)

    return render(request,
                  'edit_shop.html',
                  {'form':form})


@login_required
def add_product(request, shop_id):
    shop = get_object_or_404(Shop, id=shop_id)
    aap = AspectAwarePreprocessor(300, 165) 

    if request.method == 'POST':
        form = AddProductForm(data=request.POST, files=request.FILES)

        if form.is_valid():
            new_product = form.save(commit=False)

            # if new_product.photo:
            #     new_image = aap.preprocess(np.asarray(new_product.photo))
            #     new_product.photo = np.fromarrays(new_image)

            # if new_product.photo0:
            #     new_product.photo0 = aap.preprocess(new_product.photo0)

            # if new_product.photo1:
            #     new_product.photo1 = aap.preprocess(new_product.photo1)

            # if new_product.photo2:
            #     new_product.photo2 = aap.preprocess(new_product.photo2)

            # if new_product.photo3:
            #     new_product.photo3 = aap.preprocess(new_product.photo3)

            # if new_product.photo4:
            #     new_product.photo4 = aap.preprocess(new_product.photo4)

            # if new_product.photo5:
            #     new_product.photo5 = aap.preprocess(new_product.photo5)

            # if new_product.photo6:
            #     new_product.photo6 = aap.preprocess(new_product.photo6)

            # if new_product.photo7:
            #     new_product.photo7 = aap.preprocess(new_product.photo7)

            # if new_product.photo8:
            #     new_product.photo8 = aap.preprocess(new_product.photo8)

            # if new_product.photo9:
            #     new_product.photo9 = aap.preprocess(new_product.photo9)

            # if new_product.photo10:
            #     new_product.photo10 = aap.preprocess(new_product.photo10)

            # if new_product.photo11:
            #     new_product.photo11 = aap.preprocess(new_product.photo11)

            # if new_product.photo12:
            #     new_product.photo12 = aap.preprocess(new_product.photo12)

            # if new_product.photo13:
            #     new_product.photo13 = aap.preprocess(new_product.photo13)

            # if new_product.photo14:
            #     new_product.photo14 = aap.preprocess(new_product.photo14)

            # if new_product.photo15:
            #     new_product.photo15 = aap.preprocess(new_product.photo15)
            
            new_product.shop = shop 
            new_product.available = True # make the product available(because we are to filter available products only)
            new_product.save()  
            form.save_m2m()
            create_action(user=new_product.shop.owner, verb='', target=new_product)

            messages.success(request, 'Product added successfully,  ;-)')

            # Return to profile of user
            # return redirect(shop.owner.get_absolute_url())
            return render(request,
                        'share_product.html',
                        {'product':new_product})

    else:
        form = AddProductForm()  # render form
        messages.success(request, 'photo and video field required (video should not exceed 5mb due to loading speed).')

    return render(request,
                  'add_product.html',
                  {'shop':shop,
                   'form':form,
                   'section':'add'})


def detail(request, id):
    

    product = get_object_or_404(Product, id=id)
    shop = product.shop
    user = shop.owner


    # product ranking
    r.zincrby('product_ranking', product.id, 1)  # create a sorted set of keys.

    # total views for a product
    total_views = r.incr('product:{}:views'.format(product.id))
    product.total_views = total_views  # set total views
    product.save()  # re-save product to persist total_views to database.
    comment = False

    # get the user ids that like a product
    users_likes_ids = product.users_like.values_list('id', flat=True)
    # get the five of these users from the database
    users_likes = User.objects.filter(id__in=[users_likes_ids])
    # filter other similar product they also like of same category.
    # similar_products = []

    # for user in users_likes:
    #     for pproduct in user.product_liked.filter(category=product.category).exclude(id=product.id):
    #         similar_products.append(pproduct)

    # similar_products = similar_products[:5]
    product_tag_ids = product.tags.values_list("id", flat=True)
    similar_products = Product.objects.filter(tags__in=product_tag_ids).exclude(id=product.id)
    similar_products = similar_products.annotate(same_tags=Count("tags")).order_by("-same_tags", "-created")[:4]

    # product_users_likes = product_users_likes.annotate(taste=Count('product_liked')).order_by('-taste', '-created')[:5]

    form = CartAddForm()
    form_1 = OrderCreateForm()
    # if request if post
    if request.method == 'POST':
        
        comment_form = CommentForm(data=request.POST)  # prepopulate data with existing form.

        if comment_form.is_valid():
            if request.user.is_authenticated:
                comment = comment_form.save(commit=False)  # create comment instance but don't save to the database yet.
                comment.product = product
                comment.user = request.user
                comment.email = str(request.user.email)
                comment.save()   # save comment form
            else:
                return redirect('account:login')    

    else:
        # get comment form
        comment_form = CommentForm()
        form = CartAddForm()  # render form

    return render(request,
                  'product_detail.html',
                  {'product':product,
                   'comment':comment,
                   'total_views':total_views,
                   'comment_form':comment_form,
                   'similar_products':similar_products,
                   'form':form,
                   'form_1':form_1})

@login_required
def product_ranking(request):
    product_ranking = r.zrange('product_ranking', 0, -1, desc=True)  # get sorted set.

    product_ranking_ids = [int(id) for id in product_ranking] # get ids of products in sorted set

    most_viewed = list(Product.objects.filter(id__in=product_ranking_ids))  # get the products that are being ranked
    most_viewed.sort(key=lambda x: product_ranking_ids.index(x.id))  # order product according to their ranking.

    return render(request,
                  'ranking.html',
                  {'most_viewed':most_viewed})

@login_required
def delete(request, product_id):
    product = get_object_or_404(Product, id=product_id, shop=request.user.shop)   # get product
    # get action which has this product as it's target
    id =int(product.id)
    actions = Action.objects.filter(target_id=id)
    actions.delete()  # delete action
    Product.objects.filter(name=product.name, id=product.id).delete() # delete the product from the database.



    return redirect(request.user.get_absolute_url())


# @ajax_required
# @require_POST

bizz/templates/add_product.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title %}
    Add Property
{% endblock %}


{% block content %}
    <br/>


    {% if form.errors %}

        {% for error in form.errors %}
           Error: {{ error }} field
        {% endfor %}

    {% else %}
    <main role="main" class="container-fluid">
<div class="offset-lg-3 col-lg-6 col-md-12">
  <div >

    <form action="." method="post" enctype="multipart/form-data">
      <div class="mb-4 text-center">
      <!-- <img src="#" alt="" width="72" height="72"><br/> -->
      <!--<h1 class="h3 mb-3 font-weight-bold text-black-100 shadow-lg">Add product</h1>--><br/>
      <h3 class="h3 mb-3 font-weight-bold text-black-100 shadow-lg">Hey, {{ shop.owner.get_full_name }}</h3>
      <h4><a href='{% url 'bizz:post' request.user.id %}'>Or create post instead?</a></h4>
    </div>
      {% for field in form.visible_fields %}
        <label id="field.id_for_label">{{ field.label }}</label>
        {{ field|add_class:'form-control' }}
        {% endfor %}

        <br/>
      <div class="text-center">
          {% csrf_token %}
      <button class="btn btn-dark btn-lg" type="submit">Add property</button>
      <hr>


      </div>
        </form>
</div>
</div>
</main>
    {% endif %}<br/><br/>

{% endblock %}

bizz/templates/add_shop.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title %}Your business online!{% endblock %}

{% block content %}
    <br/>

    {% if form.errors %}

        {% for error in form.errors %}
            {{ error }}
        {% endfor %}

    {% else %}
        <br/>
          <main role="main" class="container-fluid">
<div class="offset-lg-3 col-lg-6 col-md-12">
  <div>
    <form action="." method="post" enctype="multipart/form-data">
      <div class="mb-4 text-center">
      <img src="{% static 'img/favicon.png' %}" alt="" width="72" height="72">
      <h1 class="h3 mb-3 font-weight-bold text-black-100 shadow-lg">Hello {{ user.get_full_name }}</h1>
          <h3 class="h3 mb-3 font-weight-bold text-black-100 shadow-lg">Create your company using the details below</h3>
    </div>
      {% for field in form.visible_fields %}
        <label id="field.id_for_label">{{ field.label }}</label>
        {{ field|add_class:'form-control' }}
        {% endfor %}


      <div class="text-center">
          {% csrf_token %}
      <button class="btn btn-info btn-lg" type="submit">Confirm</button>
      <hr>
      <div class="container">
       <footer class="mt-5 mb-10 text-muted text-center">&copy; 2018 Casbah.com | All rights reserved</footer>
           </div>

      </div>
        </form>
</div>
</div>
</main>

    {% endif %}
{% endblock %}

bizz/templates/edit_shop.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}


{% block title %}
    Edit your shop
{% endblock %}

{% block content %}
    <br/>
    <!--<h3 class='display-3'>Edit your shop</h3>-->

    {% if form.errors %}

        {% for error in form.errors %}
            {{ error }}
        {% endfor %}

    {% else %}

                <main role="main" class="container-fluid">
            <div class="offset-lg-3 col-lg-6 col-md-12">
              <div>
                <form action="." method="post" enctype="multipart/form-data">
                  <div class="mb-4 text-center">
                  <img src="{% static 'img/favicon.png' %}" alt="" width="72" height="72">
                  <h1 class="h3 mb-3 font-weight-bold text-black-100 shadow-lg">Edit company</h1>
                </div>
                  {% for field in form.visible_fields %}
                    <label id="field.id_for_label">{{ field.label }}</label>
                    {{ field|add_class:'form-control' }}
                    {% endfor %}
                  <div class="text-center">
                      {% csrf_token %}<br/>
                  <button class="btn btn-info btn-lg" type="submit">Update</button>
                  </div>
                    </form><br/><br/>
            </div>
            </div>
            </main><br/><br/><br/>
    {% endif %}
{% endblock %}

bizz/templates/post.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title %}Create Post{% endblock %}
{% block js %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.form/4.2.2/jquery.form.min.js"></script>
    <script>
    var main = function() {
      $('#upload').on('submit', function(e){
        e.preventDefault();
        $(this).ajaxSubmit({
          beforeSend:function(){
            $('#prog').show();
            $('#prog').attr('value', '0');
          },
          uploadProgress:function(event, position, total, percentComplete){
            $('#prog').attr('value', percentComplete);
          },
          success:function(data) {
            $('#here').html(data);
          }
        });
      }); 

    };

    $(document).ready(main);
    </script>
{% endblock %}

{% block content %}
    <br/><br/>
    {% if form.errors %}

        {% for error in form.errors %}
           Error: {{ error }} field
        {% endfor %}

    {% else %}
    <main role="main" class="container-fluid">
<div class="offset-lg-3 col-lg-6 col-md-12">
  <div >

    <form action="." method="post" enctype="multipart/form-data" id='upload'>
      <div class="mb-4 text-center">
      <img src="{% static 'img/favicon.png' %}" alt="" width="72" height="72"><br/>
      <!--<h1 class="h3 mb-3 font-weight-bold text-black-100 shadow-lg">Add product</h1>--><br/>
      <h3 class="h3 mb-3 font-weight-bold text-black-100 shadow-lg">Hey, {{ user.username }}</h3>
    </div>
      {% for field in form.visible_fields %}
        <label id="field.id_for_label">{{ field.label }}</label>
        {{ field|add_class:'form-control' }}
        {% endfor %}

        <br/>
      <div class="text-center">
          {% csrf_token %}
      <button class="btn btn-dark btn-lg" type="submit">Create Post</button><br/><br/><br/>
      <hr>


      </div>
        </form>
        <progress id='prog' max='100' value='0' style='display:none;'></progress>
        <div id='here'></div>
</div>
</div>
</main>
    {% endif %}

{% endblock %}

bizz/templates/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load account_tags %}
{% load humanize %}

{% block css %}
    <link href="{% static 'css/main.css' %}" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,700|Source+Sans+Pro:400,700" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/comment.css' %}">
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport'/>
{% endblock %}

{% block title %} Read '{{ post.title }}' by {{ post.user.get_full_name }} on www.stardaf.com{% url "bizz:post_text" post.id post.title %}{% endblock %}

{% block content %}
{% if not request.user.is_authenticated %}
    <div style='position:fixed;bottom:70px;left:20%;right:20%;z-index:10;background-color:lavender; padding:10px; border-radius:10%' class='float-center'>  
          Get in there !
        <br/>
        <span class='mx-auto d-block'>
        <a href='{% url "account:login" %}'>
            <button type="button" class="btn btn-secondary btn-sm ">
                login
            </button>
        </a>
        <a href='{% url "account:register" %}'>
            <button type="button" class="btn btn-secondary btn-sm ">
                create account
            </button>
        </a>
        </span>
    </div>
    {% endif %}
    <br/>
    
    <div class="container">
	<div class="jumbotron jumbotron-fluid mb-3 pl-0 pt-0 pb-0 bg-white position-relative">
		
			
					<p class="text-uppercase font-weight-bold">
						<a class="text-danger" href="./category.html">Stories</a>
					</p>
					<h1 class="display-4 secondfont mb-3 font-weight-bold">{{ post.title }}</h1>
					<div class="d-flex align-items-center">
						<img class="rounded-circle" src="{% if post.user.profile.image %}{{ post.user.profile.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" width="70">
						<small class="ml-2">{{ post.user.get_full_name }} <span class="text-muted d-block">{{ post.created|timesince }} ago &middot; 
                        <a href='#' data-id="{{ post.user.id }}" 
    data-action="{% if request.user in post.user.followers.all %}un{% endif %}follow"
    class='follow' id='followbutton_{{ post.id }}'>
    {% if not request.user in post.user.followers.all  %}
        <button class="btn btn-outline-primary btn-sm float-right">follow</button>
    {% else %}
        <button class="btn btn-outline-primary btn-sm float-right">unfollow</button>
    {% endif %}  
    </a></span>
						</small>
					</div>
				
				{% if not post.video %}
            <a href='{% url "bizz:post_text" post.id post.title %}'>
            <img src='{{ post.image.url }}' style='height:auto; width:100%; padding:0px; border-radius:10px 10px 10px 10px'/>
            </a>
            {% else %}
            <a href='{% url "bizz:post_text" post.id post.title %}'>
                <video width="100%" height="100%" style='border-radius:10px 10px 10px 10px'  controls {% if post.image %}poster="{{ post.image.url }}"{% endif %}>
                        <source src="{{ post.video.url }}" type="video/mp4">
                        Update your browser.
                    </video>
            </a>
            {% endif %}<br/>
			
		
	</div>
</div>

<div class="container pt-4 pb-4">
	<div class="row justify-content-center">
        

				
		</div>
		<div class="col-md-12 col-lg-8">
			<article class="article-post">
			{% if post.post %}
                <section>
                    <p>
                        {{ post.post }}
                    </p>
                </section>    
            {% endif %}
            {% if post.paragraph_1 %}
                <section>
                    <p>
                        {{ post.paragraph_1 }}
                    </p>
                </section>    
            {% endif %}
            {% if post.paragraph_2 %}
                <section>    
                    <p>
                        {{ post.paragraph_2 }}
                    </p>
                </section>    
            {% endif %}
            {% if post.paragraph_3 %}
                <section>
                    <p>
                        {{ post.paragraph_3 }}
                </section>    </p>
            {% endif %}
            {% if post.paragraph_4 %}
                <section>
                    <p>
                        {{ post.paragraph_4 }}
                    </p>
                </section>
            {% endif %}
            {% if post.paragraph_5 %}
                <section>
                    <p>
                        {{ post.paragraph_5 }}
                    </p>
                </section>
            {% endif %}
			</article>
            
			
		</div>
	</div>
</div>
<div class="sticky-top text-center">
				<div class="text-muted">
					Share this
				</div>
				<div class="share d-inline-block">
					<span class="float-right mx-2"><a onclick=''><span class='fa fa-share-alt pull-right icons fa-2x' data-toggle="modal" data-target='#exampleModalCenter_{{ post.id }}'></a></span>
				</div>
			</div>
		</div>

<div class="modal fade" id="exampleModalCenter_{{ post.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Share to friends</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
                    <!-- AddToAny BEGIN -->
            <div class="a2a_kit a2a_kit_size_32 a2a_default_style">
            <a class="a2a_dd" href="https://www.addtoany.com/share"></a>
            <a class="a2a_button_facebook"></a>
            <a class="a2a_button_twitter"></a>
            <a class="a2a_button_google_gmail"></a>
            <a class="a2a_button_whatsapp"></a>
            <a class="a2a_button_sms"></a>
            </div>
            <script async src="https://static.addtoany.com/menu/page.js"></script>
            <!-- AddToAny END -->
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        
      </div>
    </div>
  </div>
</div>
    
<div class="container pt-4 pb-4">
	<h5 class="font-weight-bold spanborder"><span>Read next</span></h5>
    {% for post in similar_posts %}
	<div class="row">
		
		{% comment %} <div class="col-lg-6">
					<a href='{% url "bizz:post_text" post.id post.title %}'><img height="80" src="{{ post.image.url }}"></a>
					<div class="pl-3">
						<h2 class="mb-2 h6 font-weight-bold">
						<a class="text-dark" href="{% url "bizz:post_text" post.id post.title %}">{{ post.title }}</a>
						</h2>
						<div class="card-text text-muted small">
							 <a href='{{ user.get_absolute_url }}'>{{ post.user.get_full_name }}</a>
						</div>
						<small class="text-muted">{{ post.created }}</small>
					</div>	
		</div> {% endcomment %}
        <div class="col-lg-6">
			<div class="card border-0 mb-4 box-shadow h-xl-300">
				<a href='{% url "bizz:post_text" post.id post.title %}'><div style="background-image: url('{{ post.image.url }}'); height: 150px; background-size: cover; background-repeat: no-repeat;"></a>
				</div>
				<div class="card-body px-0 pb-0 d-flex flex-column align-items-start">
					<h2 class="h4 font-weight-bold">
					<a  href="{% url 'bizz:post_text' post.id post.title %}">{{ post.title }}</a>
					</h2>
					<p class="card-text">
						<a class="text-dark" href="{% url 'bizz:post_text' post.id post.title %}">{{ post.post|truncatewords:20 }}</a> 
					</p>
					<div>
						<small class="d-block"><a class="text-muted" href="{{ user.get_absolute_url }}">@{{ post.user.get_full_name }}</a></small>
						
					</div>
				</div>
			</div>
		</div>
	</div><br/>
    {% endfor %}
    <span class="fa fa-2x"><h5>({{ post.post_comments.count }}) </h5></span>
    Comment{{ post.post_comments.count|pluralize }}  {% if request.user.is_anonymous %}<small style="color:red"><a href='{% url 'account:register' %}'>Create account to comment</a></small> or
                            <small style='color:blue'><a href='{% url 'account:login' %}'>Login</a></small> to comment{% endif %}
    <form action="." method="post" class='form-inline' role='form'>
                                            <div class="form-group mx-xm-3 mb-2">
                                                {% csrf_token %}
                                                
                                                {% for field in comment_form.visible_fields %}
                                                <label id="field.id_for_label">{{ field.label }}</label>
                                                {{ field|add_class:'form-control' }}
                                                
                                    
                                                <button class='btn btn-outline-primary'><span class='fa fa-paper-plane'></span></button>
                                                
                                                {% endfor %}
                                            </div>
                                        </form>
        {% for comment in post.post_comments.all %}
                <div class='comment'>
                <p class='info'>
                Comment {{ forloop.counter }} by {{ comment.user.username }} on
                    {{ comment.created|timesince }} ago
                    </p>
                        {{ comment.body|linebreaks }}
                </div>
        {% empty %}
            <p>Be the first to comment.</p>
        {% endfor %}                                    
</div><br/>


{% endblock %}

bizz/templates/ranking.html
{% extends 'base.html' %}

{% block title %}{% endblock %}

{% block content %}{% endblock %}